-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'yyyy-mm-dd')
from MEMBER_PROFILE
where TO_CHAR(DATE_OF_BIRTH, 'mm') = '03'
AND GENDER ='W'
AND TLNO is not null
order by MEMBER_ID
