-- 코드를 입력하세요
SELECT a.TITLE, a.BOARD_ID, b.REPLY_ID, b.WRITER_ID, b.CONTENTS, TO_CHAR(b.CREATED_DATE,'yyyy-mm-dd')
from USED_GOODS_BOARD a JOIN USED_GOODS_REPLY b
ON a.BOARD_ID = b.BOARD_ID
WHERE TO_CHAR(a.CREATED_DATE, 'yyyy-mm') = '2022-10'
order by b.CREATED_DATE asc, a.TITLE asc